"""Pokédex demo - Auto-generated FastAPI application.

Generated by API Maker.
Production-ready with SQLAlchemy + SQLite/PostgreSQL.
"""

from __future__ import annotations

import os
import time
import json
from contextlib import contextmanager
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional, Annotated, List, Dict, Any

from fastapi import FastAPI, HTTPException, Query, Request, Depends, Security
from fastapi.security import APIKeyHeader, HTTPBearer, HTTPAuthorizationCredentials
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker, relationship, joinedload
import jwt

# ─── Configuration ───────────────────────────────────────────────
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./data.db")
AUTH_METHOD = "none"
API_KEY = os.getenv("API_KEY", "")
JWT_SECRET = os.getenv("JWT_SECRET", "")
RATE_LIMIT = int(os.getenv("RATE_LIMIT", "0"))
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "*")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)
Base = DeclarativeBase()

# ─── Security Schemes ───────────────────────────────────────────
api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)
security_jwt = HTTPBearer(auto_error=False)

# ─── Database ──────────────────────────────────────────────────
@contextmanager
def get_db():
    """Get a database session."""
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

# ─── Models & Schemas ────────────────────────────────────────────

# --- Model for pokemon ---
class PokemonRecord(Base):
    __tablename__ = "pokemon_records"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

  
    pokedex_id: Mapped[int] = mapped_column(nullable=False)
  

  
    name: Mapped[str] = mapped_column(nullable=False)
  

  
    type: Mapped[str] = mapped_column(nullable=False)
  

  
    secondary_type: Mapped[str] | None = mapped_column(nullable=True)
  

  
    ability: Mapped[str] = mapped_column(nullable=False)
  

  
    region: Mapped[str] = mapped_column(nullable=False)
  

  
    level: Mapped[int] = mapped_column(nullable=False)
  

  
    hp: Mapped[int] = mapped_column(nullable=False)
  

  
    attack: Mapped[int] = mapped_column(nullable=False)
  

  
    defense: Mapped[int] = mapped_column(nullable=False)
  

  
    speed: Mapped[int] = mapped_column(nullable=False)
  

  
    legendary: Mapped[bool] = mapped_column(nullable=False)
  

  
    caught_at: Mapped[datetime] | None = mapped_column(nullable=True)
  

    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

  

class PokemonCreate(BaseModel):

    pokedex_id: int

    name: str

    type: str

    secondary_type: str | None = None

    ability: str

    region: str

    level: int

    hp: int

    attack: int

    defense: int

    speed: int

    legendary: bool

    caught_at: datetime | None = None


class PokemonUpdate(BaseModel):

    pokedex_id: int

    name: str

    type: str

    secondary_type: str | None = None

    ability: str

    region: str

    level: int

    hp: int

    attack: int

    defense: int

    speed: int

    legendary: bool

    caught_at: datetime | None = None


class PokemonResponse(BaseModel):
    id: int

    pokedex_id: int

    name: str

    type: str

    secondary_type: str | None

    ability: str

    region: str

    level: int

    hp: int

    attack: int

    defense: int

    speed: int

    legendary: bool

    caught_at: datetime | None

    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}


# --- Model for trainers ---
class TrainersRecord(Base):
    __tablename__ = "trainers_records"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

  
    trainer_id: Mapped[int] = mapped_column(nullable=False)
  

  
    name: Mapped[str] = mapped_column(nullable=False)
  

  
    team: Mapped[str] = mapped_column(nullable=False)
  

  
    badge_count: Mapped[int] = mapped_column(nullable=False)
  

  
    region: Mapped[str] = mapped_column(nullable=False)
  

  
    pokemon_ids: Mapped[str] | None = mapped_column(nullable=True)
  

    created_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

  

class TrainersCreate(BaseModel):

    trainer_id: int

    name: str

    team: str

    badge_count: int

    region: str

    pokemon_ids: str | None = None


class TrainersUpdate(BaseModel):

    trainer_id: int

    name: str

    team: str

    badge_count: int

    region: str

    pokemon_ids: str | None = None


class TrainersResponse(BaseModel):
    id: int

    trainer_id: int

    name: str

    team: str

    badge_count: int

    region: str

    pokemon_ids: str | None

    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}



# ─── Auth Dependency ─────────────────────────────────────────────
async def verify_auth(
    api_key: Optional[str] = Security(api_key_header),
    token: Optional[HTTPAuthorizationCredentials] = Security(security_jwt)
):
    if AUTH_METHOD == "apikey":
        if not api_key or api_key != API_KEY:
            raise HTTPException(status_code=401, detail="Invalid or missing API Key")
    elif AUTH_METHOD == "jwt":
        if not token:
            raise HTTPException(status_code=401, detail="Missing Bearer Token")
        try:
            jwt.decode(token.credentials, JWT_SECRET, algorithms=["HS256"])
        except Exception:
            raise HTTPException(status_code=401, detail="Invalid or expired JWT")
    return True

# ─── Rate Limiting ────────────────────────────────────────────────
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

limiter = Limiter(key_func=get_remote_address, enabled=RATE_LIMIT > 0)

# ─── Application ─────────────────────────────────────────────────
app = FastAPI(
    title="Pokédex demo",
    description="""API en memoria para listar, registrar y actualizar Pokémon y entrenadores favoritos""",
    version="0.1.0",
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS.split(",") if CORS_ORIGINS != "*" else ["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)



@app.on_event("startup")
def startup():
    Base.metadata.create_all(bind=engine)
    
    data_path = Path("data.json")
    if data_path.exists():
        with open(data_path, "r", encoding="utf-8") as f:
            all_data = json.load(f)
            with get_db() as db:

                if "pokemon" in all_data:
                    count = db.query(PokemonRecord).count()
                    if count == 0:
                        print(f"Seeding pokemon...")
                        for row in all_data["pokemon"]:
                            valid_data = {k: v for k, v in row.items() if k in PokemonRecord.__table__.columns}
                            db.add(PokemonRecord(**valid_data))

                if "trainers" in all_data:
                    count = db.query(TrainersRecord).count()
                    if count == 0:
                        print(f"Seeding trainers...")
                        for row in all_data["trainers"]:
                            valid_data = {k: v for k, v in row.items() if k in TrainersRecord.__table__.columns}
                            db.add(TrainersRecord(**valid_data))

                db.commit()
    

# ─── Endpoints ───────────────────────────────────────────────────



































@app.get("/health")
def health():
    return {"status": "ok"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)