#!/bin/bash

# --- Pokédex demo Setup Script ---
# Generated by API Maker

echo "🚀 Iniciando configuración de Pokédex demo..."

# 1. Crear archivo .env si no existe
if [ ! -f .env ]; then
    echo "📝 Creando archivo .env..."
    cat <<EOF > .env
PORT=8000
DATABASE_URL=sqlite:///./data.db
API_KEY=
JWT_SECRET=
AUTH_METHOD=none
RATE_LIMIT=0
EOF
    echo "✅ Archivo .env creado."
fi

# 2. Preguntar por Docker
read -p "¿Deseas usar Docker para el despliegue? (s/n): " use_docker

if [[ $use_docker =~ ^[Ss]$ ]]; then
    echo "🐳 Iniciando con Docker Compose..."
    if command -v docker-compose >/dev/null 2>&1; then
        docker-compose up -d --build
    else
        docker compose up -d --build
    fi
    echo "✅ API levantada en Docker!"
    echo "📍 URL: http://localhost:8000"
    echo "📚 Docs: http://localhost:8000/docs"
else
    # Instalación local
    echo "💻 Iniciando instalación local..."
    
    if command -v python3 >/dev/null 2>&1; then
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        echo "✅ Entorno Python configurado."
        echo "🚀 Para arrancar: source .venv/bin/activate && python main.py"
    else
        echo "❌ Python 3 no encontrado. Por favor instálalo o usa Docker."
    fi
    
fi

echo "---"
echo "✨ ¡Todo listo! Tu API 'Pokédex demo' está configurada."