"""Code generator service — renders Jinja2 templates and produces zip bundles."""

from __future__ import annotations

import zipfile
from io import BytesIO
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from ..config import get_settings
from ..db_models import Dataset, DatasetField, Endpoint
from ..models import GenerationRequest, GenerationResult
from .project_service import project_service


TEMPLATE_DIR = Path(__file__).resolve().parent.parent.parent.parent / "generator" / "templates"

FIELD_TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "float": "float",
    "boolean": "bool",
    "datetime": "datetime",
}


def _get_python_type(field_type: str) -> str:
    return FIELD_TYPE_MAP.get(field_type, "str")


def _extract_path_param(path: str) -> str:
    """Extract path param name from a route like /items/{id}."""
    if "{" in path:
        return path.split("{")[1].split("}")[0]
    return "item_id"


def _build_context(
    project_name: str,
    project_description: str | None,
    dataset: Dataset | None,
    fields: list[DatasetField],
    endpoints: list[Endpoint],
) -> dict:
    """Build the Jinja2 template context."""
    dataset_context = None
    if dataset:
        dataset_context = {
            "name": dataset.name,
            "fields": [
                {
                    "name": f.name,
                    "type": f.field_type,
                    "python_type": _get_python_type(f.field_type),
                    "required": f.required,
                    "description": f.description,
                }
                for f in fields
            ],
        }

    endpoints_context = [
        {
            "name": ep.name,
            "method": ep.method,
            "path": ep.path,
            "summary": ep.summary,
        }
        for ep in endpoints
    ]

    return {
        "project_name": project_name,
        "project_description": project_description or "",
        "dataset": dataset_context,
        "endpoints": endpoints_context,
    }


def render_fastapi_bundle(
    project_name: str,
    project_description: str | None,
    dataset: Dataset | None,
    fields: list[DatasetField],
    endpoints: list[Endpoint],
) -> bytes:
    """Render a FastAPI project bundle as zip bytes."""
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR / "fastapi")),
        autoescape=select_autoescape(),
    )
    env.filters["capitalize"] = lambda s: s.capitalize() if s else ""
    env.filters["lower"] = lambda s: s.lower() if s else ""
    env.filters["replace"] = lambda s, old, new: s.replace(old, new) if s else ""
    env.filters["extract_path_param"] = _extract_path_param

    context = _build_context(project_name, project_description, dataset, fields, endpoints)

    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Render main.py
        main_tpl = env.get_template("main.py.j2")
        zf.writestr("main.py", main_tpl.render(**context))

        # Render requirements.txt
        req_tpl = env.get_template("requirements.txt.j2")
        zf.writestr("requirements.txt", req_tpl.render())

        # Render Dockerfile
        docker_tpl = env.get_template("Dockerfile.j2")
        zf.writestr("Dockerfile", docker_tpl.render())

        # README
        zf.writestr(
            "README.md",
            f"# {project_name}\n\nAuto-generated by API Maker.\n\n"
            f"## Run\n```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```\n\n"
            f"## Docker\n```bash\ndocker build -t {project_name.lower().replace(' ', '-')} .\ndocker run -p 8000:8000 {project_name.lower().replace(' ', '-')}\n```\n",
        )

    buf.seek(0)
    return buf.getvalue()


def run_generation(
    session, project_id, payload: GenerationRequest
) -> GenerationResult:
    """Generate code bundle for a project."""
    from sqlmodel import select

    project_service.mark_status(session, project_id, "building")

    # Get project data
    data = project_service.get_project_with_data(session, project_id)
    project = data["project"]
    dataset = data["dataset"]
    fields = data["fields"]
    endpoints = data["endpoints"]

    # If no endpoints defined, create a default one so generation still works
    if not endpoints:
        from ..db_models import Endpoint as DBEndpoint
        session.add(DBEndpoint(
            project_id=str(project.id),
            name="Default",
            method="GET",
            path="/records",
            summary="Default endpoint",
        ))
        session.flush()
        endpoints = session.exec(
            select(DBEndpoint).where(DBEndpoint.project_id == str(project.id))
        ).all()

    try:
        # Generate FastAPI bundle
        zip_bytes = render_fastapi_bundle(
            project.name,
            project.description,
            dataset,
            fields,
            endpoints,
        )

        # Save to artifacts
        artifacts_root = Path("artifacts") / str(project.id)
        artifacts_root.mkdir(parents=True, exist_ok=True)

        bundle_path = artifacts_root / f"{project.target_stack}-bundle.zip"
        bundle_path.write_bytes(zip_bytes)

        # Save OpenAPI spec
        from ..openapi_builder import build_openapi_document
        from ..models import Project as PydanticProject

        pydantic_project = PydanticProject(
            id=project.id,
            name=project.name,
            description=project.description,
            target_stack=project.target_stack,
            dataset=None,
            endpoints=[
                {"id": ep.id, "name": ep.name, "method": ep.method, "path": ep.path, "summary": ep.summary}
                for ep in endpoints
            ],
            status=project.status,
            created_at=project.created_at,
            updated_at=project.updated_at,
        )
        import json
        openapi_doc = build_openapi_document(pydantic_project)
        openapi_path = artifacts_root / "openapi.json"
        openapi_path.write_text(json.dumps(openapi_doc, indent=2, ensure_ascii=False))
    except Exception as e:
        project_service.mark_status(session, project_id, "draft")
        raise e

    sdk_paths = []
    if payload.include_sdk:
        sdk_dir = artifacts_root / "sdks"
        sdk_dir.mkdir(parents=True, exist_ok=True)
        sdk_paths.append(str(sdk_dir / "typescript"))
        sdk_paths.append(str(sdk_dir / "python"))

    project_service.mark_status(session, project_id, "ready")

    return GenerationResult(
        project_id=project.id,
        openapi_path=str(openapi_path),
        bundle_path=str(bundle_path),
        sdk_paths=sdk_paths,
    )
