"""add users workspaces workspace_members

Revision ID: aa843183eab7
Revises: 76667e06f04c
Create Date: 2026-05-09 01:25:42.373053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'aa843183eab7'
down_revision: Union[str, Sequence[str], None] = '76667e06f04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('workspace_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dataset_fields', 'dataset_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('datasets', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('endpoints', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # SQLite requires batch operations for adding columns with foreign keys
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_projects_workspace_id', 'workspaces', ['workspace_id'], ['id'])
        batch_op.create_foreign_key('fk_projects_created_by', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_workspace_id', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('workspace_id')
    op.alter_column('endpoints', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('datasets', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dataset_fields', 'dataset_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
